name: Rotina de Execução de Testes

on:
  push:
    branches: [ delita ]
  pull_request:
    branches: [ delita ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Usando Node.js ${{ matrix.node-version }} e Executando Testes
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: yarn cy:to-do-mvc

  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: 'Realizando Upload de Artefatos de Teste'
      uses: actions/upload-artifact@v3
      with:
        name: evidencias
        path: report/
        retention-days: 1
