# This is a basic workflow to help you get started with Actions

name: Rotina Testes

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, World

  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: yarn 
