# This is a basic workflow to help you get started with Actions

name: Rotina Testes

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          yarn 
          yarn cy:to-do-mvc
