# This is a basic workflow to help you get started with Actions

name: Rotina Testes

on:
  workflow_dispatch:

jobs:
  pre-teste:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: yarn 

  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: yarn cy:to-do-mvc
