# This is a basic workflow to help you get started with Actions

name: Rotina Testes

on:
  push:
    branches:
      - delita

jobs:
  pre-testes:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: yarn 
        
  testes:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-todomvc
    steps:
      - name: Run Tests
        run: yarn cy:to-do-mvc
